services:
  - type: web
    name: air-quality-sri-lanka
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r Backend/requirements.txt
    startCommand: gunicorn -c gunicorn_config.py Backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000